// Currency data for multi-currency system - Organized alphabetically
export const currencies = [
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    country: "Argentina",
    flag: "🇦🇷",
    timezone: "America/Argentina/Buenos_Aires",
    locale: "es-AR",
    rate: 367.5,
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    country: "Australia",
    flag: "🇦🇺",
    timezone: "Australia/Sydney",
    locale: "en-AU",
    rate: 1.53,
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: "BD",
    country: "Bahrain",
    flag: "🇧🇭",
    timezone: "Asia/Bahrain",
    locale: "ar-BH",
    rate: 0.38,
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    country: "Brazil",
    flag: "🇧🇷",
    timezone: "America/Sao_Paulo",
    locale: "pt-BR",
    rate: 4.92,
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    country: "Canada",
    flag: "🇨🇦",
    timezone: "America/Toronto",
    locale: "en-CA",
    rate: 1.36,
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    country: "Switzerland",
    flag: "🇨🇭",
    timezone: "Europe/Zurich",
    locale: "de-CH",
    rate: 0.88,
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "$",
    country: "Chile",
    flag: "🇨🇱",
    timezone: "America/Santiago",
    locale: "es-CL",
    rate: 875.5,
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    country: "China",
    flag: "🇨🇳",
    timezone: "Asia/Shanghai",
    locale: "zh-CN",
    rate: 7.24,
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "$",
    country: "Colombia",
    flag: "🇨🇴",
    timezone: "America/Bogota",
    locale: "es-CO",
    rate: 3925.0,
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    country: "Czech Republic",
    flag: "🇨🇿",
    timezone: "Europe/Prague",
    locale: "cs-CZ",
    rate: 22.75,
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    country: "Denmark",
    flag: "🇩🇰",
    timezone: "Europe/Copenhagen",
    locale: "da-DK",
    rate: 6.88,
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "E£",
    country: "Egypt",
    flag: "🇪🇬",
    timezone: "Africa/Cairo",
    locale: "ar-EG",
    rate: 30.9,
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    country: "European Union",
    flag: "🇪🇺",
    timezone: "Europe/Paris",
    locale: "de-DE",
    rate: 0.92,
  },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    country: "United Kingdom",
    flag: "🇬🇧",
    timezone: "Europe/London",
    locale: "en-GB",
    rate: 0.79,
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    country: "Hong Kong",
    flag: "🇭🇰",
    timezone: "Asia/Hong_Kong",
    locale: "zh-HK",
    rate: 7.82,
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    symbol: "₪",
    country: "Israel",
    flag: "🇮🇱",
    timezone: "Asia/Jerusalem",
    locale: "he-IL",
    rate: 3.72,
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    country: "India",
    flag: "🇮🇳",
    timezone: "Asia/Kolkata",
    locale: "hi-IN",
    rate: 83.12,
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    country: "Japan",
    flag: "🇯🇵",
    timezone: "Asia/Tokyo",
    locale: "ja-JP",
    rate: 149.5,
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    country: "South Korea",
    flag: "🇰🇷",
    timezone: "Asia/Seoul",
    locale: "ko-KR",
    rate: 1318.42,
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "KD",
    country: "Kuwait",
    flag: "🇰🇼",
    timezone: "Asia/Kuwait",
    locale: "ar-KW",
    rate: 0.31,
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    country: "Mexico",
    flag: "🇲🇽",
    timezone: "America/Mexico_City",
    locale: "es-MX",
    rate: 17.18,
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    country: "Malaysia",
    flag: "🇲🇾",
    timezone: "Asia/Kuala_Lumpur",
    locale: "ms-MY",
    rate: 4.65,
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    country: "Nigeria",
    flag: "🇳🇬",
    timezone: "Africa/Lagos",
    locale: "en-NG",
    rate: 777.25,
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    country: "Norway",
    flag: "🇳🇴",
    timezone: "Europe/Oslo",
    locale: "nb-NO",
    rate: 10.89,
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    country: "New Zealand",
    flag: "🇳🇿",
    timezone: "Pacific/Auckland",
    locale: "en-NZ",
    rate: 1.66,
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    country: "Philippines",
    flag: "🇵🇭",
    timezone: "Asia/Manila",
    locale: "en-PH",
    rate: 55.85,
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    country: "Pakistan",
    flag: "🇵🇰",
    timezone: "Asia/Karachi",
    locale: "ur-PK",
    rate: 279.5,
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    country: "Poland",
    flag: "🇵🇱",
    timezone: "Europe/Warsaw",
    locale: "pl-PL",
    rate: 4.05,
  },
  {
    code: "QAR",
    name: "Qatari Rial",
    symbol: "QR",
    country: "Qatar",
    flag: "🇶🇦",
    timezone: "Asia/Qatar",
    locale: "ar-QA",
    rate: 3.64,
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    country: "Russia",
    flag: "🇷🇺",
    timezone: "Europe/Moscow",
    locale: "ru-RU",
    rate: 92.35,
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "SR",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    timezone: "Asia/Riyadh",
    locale: "ar-SA",
    rate: 3.75,
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    country: "Sweden",
    flag: "🇸🇪",
    timezone: "Europe/Stockholm",
    locale: "sv-SE",
    rate: 10.71,
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    country: "Singapore",
    flag: "🇸🇬",
    timezone: "Asia/Singapore",
    locale: "en-SG",
    rate: 1.35,
  },
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    country: "Thailand",
    flag: "🇹🇭",
    timezone: "Asia/Bangkok",
    locale: "th-TH",
    rate: 35.25,
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    country: "Turkey",
    flag: "🇹🇷",
    timezone: "Europe/Istanbul",
    locale: "tr-TR",
    rate: 28.74,
  },
  {
    code: "TWD",
    name: "Taiwan Dollar",
    symbol: "NT$",
    country: "Taiwan",
    flag: "🇹🇼",
    timezone: "Asia/Taipei",
    locale: "zh-TW",
    rate: 31.85,
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    country: "Ukraine",
    flag: "🇺🇦",
    timezone: "Europe/Kyiv",
    locale: "uk-UA",
    rate: 38.95,
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    country: "United States",
    flag: "🇺🇸",
    timezone: "America/New_York",
    locale: "en-US",
    rate: 1.0,
  },
  {
    code: "VEF",
    name: "Venezuelan Bolívar",
    symbol: "Bs",
    country: "Venezuela",
    flag: "🇻🇪",
    timezone: "America/Caracas",
    locale: "es-VE",
    rate: 36.5,
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    country: "Vietnam",
    flag: "🇻🇳",
    timezone: "Asia/Ho_Chi_Minh",
    locale: "vi-VN",
    rate: 24245.0,
  },
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    country: "South Africa",
    flag: "🇿🇦",
    timezone: "Africa/Johannesburg",
    locale: "en-ZA",
    rate: 19.12,
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    symbol: "ZK",
    country: "Zambia",
    flag: "🇿🇲",
    timezone: "Africa/Lusaka",
    locale: "en-ZM",
    rate: 24.75,
  },
  // Additional world currencies
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    country: "Afghanistan",
    flag: "🇦🇫",
    timezone: "Asia/Kabul",
    locale: "fa-AF",
    rate: 71.25,
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    symbol: "L",
    country: "Albania",
    flag: "🇦🇱",
    timezone: "Europe/Tirane",
    locale: "sq-AL",
    rate: 95.5,
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "֏",
    country: "Armenia",
    flag: "🇦🇲",
    timezone: "Asia/Yerevan",
    locale: "hy-AM",
    rate: 387.5,
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    symbol: "Kz",
    country: "Angola",
    flag: "🇦🇴",
    timezone: "Africa/Luanda",
    locale: "pt-AO",
    rate: 505.25,
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    country: "Azerbaijan",
    flag: "🇦🇿",
    timezone: "Asia/Baku",
    locale: "az-AZ",
    rate: 1.7,
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    country: "Bangladesh",
    flag: "🇧🇩",
    timezone: "Asia/Dhaka",
    locale: "bn-BD",
    rate: 109.75,
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    symbol: "лв",
    country: "Bulgaria",
    flag: "🇧🇬",
    timezone: "Europe/Sofia",
    locale: "bg-BG",
    rate: 1.8,
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "FBu",
    country: "Burundi",
    flag: "🇧🇮",
    timezone: "Africa/Bujumbura",
    locale: "fr-BI",
    rate: 2850.0,
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "B$",
    country: "Brunei",
    flag: "🇧🇳",
    timezone: "Asia/Brunei",
    locale: "ms-BN",
    rate: 1.35,
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "Bs",
    country: "Bolivia",
    flag: "🇧🇴",
    timezone: "America/La_Paz",
    locale: "es-BO",
    rate: 6.9,
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "B$",
    country: "Bahamas",
    flag: "🇧🇸",
    timezone: "America/Nassau",
    locale: "en-BS",
    rate: 1.0,
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    country: "Bhutan",
    flag: "🇧🇹",
    timezone: "Asia/Thimphu",
    locale: "dz-BT",
    rate: 83.12,
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    symbol: "P",
    country: "Botswana",
    flag: "🇧🇼",
    timezone: "Africa/Gaborone",
    locale: "en-BW",
    rate: 13.45,
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "Br",
    country: "Belarus",
    flag: "🇧🇾",
    timezone: "Europe/Minsk",
    locale: "be-BY",
    rate: 3.25,
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "BZ$",
    country: "Belize",
    flag: "🇧🇿",
    timezone: "America/Belize",
    locale: "en-BZ",
    rate: 2.0,
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    country: "Democratic Republic of Congo",
    flag: "🇨🇩",
    timezone: "Africa/Kinshasa",
    locale: "fr-CD",
    rate: 2750.0,
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    country: "Costa Rica",
    flag: "🇨🇷",
    timezone: "America/Costa_Rica",
    locale: "es-CR",
    rate: 545.5,
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: "₱",
    country: "Cuba",
    flag: "🇨🇺",
    timezone: "America/Havana",
    locale: "es-CU",
    rate: 24.0,
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    symbol: "$",
    country: "Cape Verde",
    flag: "🇨🇻",
    timezone: "Atlantic/Cape_Verde",
    locale: "pt-CV",
    rate: 102.75,
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    symbol: "Fdj",
    country: "Djibouti",
    flag: "🇩🇯",
    timezone: "Africa/Djibouti",
    locale: "fr-DJ",
    rate: 177.5,
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "RD$",
    country: "Dominican Republic",
    flag: "🇩🇴",
    timezone: "America/Santo_Domingo",
    locale: "es-DO",
    rate: 56.85,
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    symbol: "دج",
    country: "Algeria",
    flag: "🇩🇿",
    timezone: "Africa/Algiers",
    locale: "ar-DZ",
    rate: 135.25,
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    symbol: "Nfk",
    country: "Eritrea",
    flag: "🇪🇷",
    timezone: "Africa/Asmara",
    locale: "ti-ER",
    rate: 15.0,
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    country: "Ethiopia",
    flag: "🇪🇹",
    timezone: "Africa/Addis_Ababa",
    locale: "am-ET",
    rate: 56.5,
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "FJ$",
    country: "Fiji",
    flag: "🇫🇯",
    timezone: "Pacific/Fiji",
    locale: "en-FJ",
    rate: 2.25,
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    country: "Georgia",
    flag: "🇬🇪",
    timezone: "Asia/Tbilisi",
    locale: "ka-GE",
    rate: 2.7,
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "GH₵",
    country: "Ghana",
    flag: "🇬🇭",
    timezone: "Africa/Accra",
    locale: "en-GH",
    rate: 12.15,
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    symbol: "D",
    country: "Gambia",
    flag: "🇬🇲",
    timezone: "Africa/Banjul",
    locale: "en-GM",
    rate: 61.5,
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    symbol: "FG",
    country: "Guinea",
    flag: "🇬🇳",
    timezone: "Africa/Conakry",
    locale: "fr-GN",
    rate: 8575.0,
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    country: "Guatemala",
    flag: "🇬🇹",
    timezone: "America/Guatemala",
    locale: "es-GT",
    rate: 7.8,
  },
  {
    code: "GYD",
    name: "Guyana Dollar",
    symbol: "G$",
    country: "Guyana",
    flag: "🇬🇾",
    timezone: "America/Guyana",
    locale: "en-GY",
    rate: 209.5,
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    symbol: "L",
    country: "Honduras",
    flag: "🇭🇳",
    timezone: "America/Tegucigalpa",
    locale: "es-HN",
    rate: 24.75,
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    symbol: "kn",
    country: "Croatia",
    flag: "🇭🇷",
    timezone: "Europe/Zagreb",
    locale: "hr-HR",
    rate: 7.15,
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    symbol: "G",
    country: "Haiti",
    flag: "🇭🇹",
    timezone: "America/Port-au-Prince",
    locale: "fr-HT",
    rate: 132.5,
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "ع.د",
    country: "Iraq",
    flag: "🇮🇶",
    timezone: "Asia/Baghdad",
    locale: "ar-IQ",
    rate: 1310.0,
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    symbol: "﷼",
    country: "Iran",
    flag: "🇮🇷",
    timezone: "Asia/Tehran",
    locale: "fa-IR",
    rate: 42000.0,
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    country: "Iceland",
    flag: "🇮🇸",
    timezone: "Atlantic/Reykjavik",
    locale: "is-IS",
    rate: 137.5,
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "JD",
    country: "Jordan",
    flag: "🇯🇴",
    timezone: "Asia/Amman",
    locale: "ar-JO",
    rate: 0.71,
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    country: "Kenya",
    flag: "🇰🇪",
    timezone: "Africa/Nairobi",
    locale: "sw-KE",
    rate: 147.5,
  },
  {
    code: "KGS",
    name: "Kyrgyzstani Som",
    symbol: "с",
    country: "Kyrgyzstan",
    flag: "🇰🇬",
    timezone: "Asia/Bishkek",
    locale: "ky-KG",
    rate: 89.5,
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    symbol: "៛",
    country: "Cambodia",
    flag: "🇰🇭",
    timezone: "Asia/Phnom_Penh",
    locale: "km-KH",
    rate: 4100.0,
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    symbol: "CF",
    country: "Comoros",
    flag: "🇰🇲",
    timezone: "Indian/Comoro",
    locale: "ar-KM",
    rate: 452.5,
  },
  {
    code: "LAK",
    name: "Lao Kip",
    symbol: "₭",
    country: "Laos",
    flag: "🇱🇦",
    timezone: "Asia/Vientiane",
    locale: "lo-LA",
    rate: 18500.0,
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "ل.ل",
    country: "Lebanon",
    flag: "🇱🇧",
    timezone: "Asia/Beirut",
    locale: "ar-LB",
    rate: 89500.0,
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    country: "Sri Lanka",
    flag: "🇱🇰",
    timezone: "Asia/Colombo",
    locale: "si-LK",
    rate: 298.5,
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    symbol: "L$",
    country: "Liberia",
    flag: "🇱🇷",
    timezone: "Africa/Monrovia",
    locale: "en-LR",
    rate: 1.0,
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    symbol: "L",
    country: "Lesotho",
    flag: "🇱🇸",
    timezone: "Africa/Maseru",
    locale: "en-LS",
    rate: 19.12,
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    symbol: "LD",
    country: "Libya",
    flag: "🇱🇾",
    timezone: "Africa/Tripoli",
    locale: "ar-LY",
    rate: 4.85,
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "DH",
    country: "Morocco",
    flag: "🇲🇦",
    timezone: "Africa/Casablanca",
    locale: "ar-MA",
    rate: 9.95,
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    symbol: "L",
    country: "Moldova",
    flag: "🇲🇩",
    timezone: "Europe/Chisinau",
    locale: "ro-MD",
    rate: 17.85,
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    symbol: "Ar",
    country: "Madagascar",
    flag: "🇲🇬",
    timezone: "Indian/Antananarivo",
    locale: "mg-MG",
    rate: 4525.0,
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "ден",
    country: "North Macedonia",
    flag: "🇲🇰",
    timezone: "Europe/Skopje",
    locale: "mk-MK",
    rate: 57.5,
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    symbol: "K",
    country: "Myanmar",
    flag: "🇲🇲",
    timezone: "Asia/Yangon",
    locale: "my-MM",
    rate: 2100.0,
  },
  {
    code: "MNT",
    name: "Mongolian Tögrög",
    symbol: "₮",
    country: "Mongolia",
    flag: "🇲🇳",
    timezone: "Asia/Ulaanbaatar",
    locale: "mn-MN",
    rate: 3385.0,
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    symbol: "MOP$",
    country: "Macau",
    flag: "🇲🇴",
    timezone: "Asia/Macau",
    locale: "zh-MO",
    rate: 8.05,
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    symbol: "Rs",
    country: "Mauritius",
    flag: "🇲🇺",
    timezone: "Indian/Mauritius",
    locale: "en-MU",
    rate: 45.75,
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    symbol: "Rf",
    country: "Maldives",
    flag: "🇲🇻",
    timezone: "Indian/Maldives",
    locale: "dv-MV",
    rate: 15.45,
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    symbol: "MK",
    country: "Malawi",
    flag: "🇲🇼",
    timezone: "Africa/Blantyre",
    locale: "en-MW",
    rate: 1625.0,
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MTn",
    country: "Mozambique",
    flag: "🇲🇿",
    timezone: "Africa/Maputo",
    locale: "pt-MZ",
    rate: 63.75,
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    symbol: "N$",
    country: "Namibia",
    flag: "🇳🇦",
    timezone: "Africa/Windhoek",
    locale: "en-NA",
    rate: 19.12,
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "Rs",
    country: "Nepal",
    flag: "🇳🇵",
    timezone: "Asia/Kathmandu",
    locale: "ne-NP",
    rate: 132.85,
  },
  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "ر.ع.",
    country: "Oman",
    flag: "🇴🇲",
    timezone: "Asia/Muscat",
    locale: "ar-OM",
    rate: 0.39,
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    symbol: "B/.",
    country: "Panama",
    flag: "🇵🇦",
    timezone: "America/Panama",
    locale: "es-PA",
    rate: 1.0,
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    country: "Peru",
    flag: "🇵🇪",
    timezone: "America/Lima",
    locale: "es-PE",
    rate: 3.75,
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "K",
    country: "Papua New Guinea",
    flag: "🇵🇬",
    timezone: "Pacific/Port_Moresby",
    locale: "en-PG",
    rate: 3.85,
  },
  {
    code: "PYG",
    name: "Paraguayan Guaraní",
    symbol: "₲",
    country: "Paraguay",
    flag: "🇵🇾",
    timezone: "America/Asuncion",
    locale: "es-PY",
    rate: 7350.0,
  },
  {
    code: "RON",
    name: "Romanian Leu",
    symbol: "lei",
    country: "Romania",
    flag: "🇷🇴",
    timezone: "Europe/Bucharest",
    locale: "ro-RO",
    rate: 4.6,
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    symbol: "дин",
    country: "Serbia",
    flag: "🇷🇸",
    timezone: "Europe/Belgrade",
    locale: "sr-RS",
    rate: 107.5,
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    symbol: "FRw",
    country: "Rwanda",
    flag: "🇷🇼",
    timezone: "Africa/Kigali",
    locale: "rw-RW",
    rate: 1310.0,
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "SI$",
    country: "Solomon Islands",
    flag: "🇸🇧",
    timezone: "Pacific/Guadalcanal",
    locale: "en-SB",
    rate: 8.15,
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    symbol: "Rs",
    country: "Seychelles",
    flag: "🇸🇨",
    timezone: "Indian/Mahe",
    locale: "en-SC",
    rate: 14.75,
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    symbol: "ج.س.",
    country: "Sudan",
    flag: "🇸🇩",
    timezone: "Africa/Khartoum",
    locale: "ar-SD",
    rate: 600.0,
  },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    country: "Sierra Leone",
    flag: "🇸🇱",
    timezone: "Africa/Freetown",
    locale: "en-SL",
    rate: 22750.0,
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    symbol: "Sh.so.",
    country: "Somalia",
    flag: "🇸🇴",
    timezone: "Africa/Mogadishu",
    locale: "so-SO",
    rate: 570.0,
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    symbol: "$",
    country: "Suriname",
    flag: "🇸🇷",
    timezone: "America/Paramaribo",
    locale: "nl-SR",
    rate: 34.5,
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    symbol: "£",
    country: "South Sudan",
    flag: "🇸🇸",
    timezone: "Africa/Juba",
    locale: "en-SS",
    rate: 185.25,
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    country: "São Tomé and Príncipe",
    flag: "🇸🇹",
    timezone: "Africa/Sao_Tome",
    locale: "pt-ST",
    rate: 22450.0,
  },
  {
    code: "SVC",
    name: "Salvadoran Colón",
    symbol: "₡",
    country: "El Salvador",
    flag: "🇸🇻",
    timezone: "America/El_Salvador",
    locale: "es-SV",
    rate: 8.75,
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    symbol: "£S",
    country: "Syria",
    flag: "🇸🇾",
    timezone: "Asia/Damascus",
    locale: "ar-SY",
    rate: 2512.5,
  },
  {
    code: "SZL",
    name: "Eswatini Lilangeni",
    symbol: "E",
    country: "Eswatini",
    flag: "🇸🇿",
    timezone: "Africa/Mbabane",
    locale: "en-SZ",
    rate: 19.12,
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "SM",
    country: "Tajikistan",
    flag: "🇹🇯",
    timezone: "Asia/Dushanbe",
    locale: "tg-TJ",
    rate: 10.95,
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    symbol: "m",
    country: "Turkmenistan",
    flag: "🇹🇲",
    timezone: "Asia/Ashgabat",
    locale: "tk-TM",
    rate: 3.45,
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: "د.ت",
    country: "Tunisia",
    flag: "🇹🇳",
    timezone: "Africa/Tunis",
    locale: "ar-TN",
    rate: 3.1,
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    symbol: "T$",
    country: "Tonga",
    flag: "🇹🇴",
    timezone: "Pacific/Tongatapu",
    locale: "to-TO",
    rate: 2.35,
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    timezone: "America/Port_of_Spain",
    locale: "en-TT",
    rate: 6.75,
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
    country: "Tanzania",
    flag: "🇹🇿",
    timezone: "Africa/Dar_es_Salaam",
    locale: "sw-TZ",
    rate: 2475.0,
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    country: "Uganda",
    flag: "🇺🇬",
    timezone: "Africa/Kampala",
    locale: "en-UG",
    rate: 3775.0,
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    symbol: "$U",
    country: "Uruguay",
    flag: "🇺🇾",
    timezone: "America/Montevideo",
    locale: "es-UY",
    rate: 38.75,
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "сўм",
    country: "Uzbekistan",
    flag: "🇺🇿",
    timezone: "Asia/Tashkent",
    locale: "uz-UZ",
    rate: 12650.0,
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    symbol: "VT",
    country: "Vanuatu",
    flag: "🇻🇺",
    timezone: "Pacific/Efate",
    locale: "en-VU",
    rate: 119.5,
  },
  {
    code: "WST",
    name: "Samoan Tālā",
    symbol: "WS$",
    country: "Samoa",
    flag: "🇼🇸",
    timezone: "Pacific/Apia",
    locale: "en-WS",
    rate: 2.75,
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    country: "Central African Republic",
    flag: "🇨🇫",
    timezone: "Africa/Bangui",
    locale: "fr-CF",
    rate: 607.5,
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "$",
    country: "East Caribbean States",
    flag: "🇦🇮",
    timezone: "America/Antigua",
    locale: "en-XC",
    rate: 2.7,
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "CFA",
    country: "West African States",
    flag: "🇧🇯",
    timezone: "Africa/Abidjan",
    locale: "fr-BJ",
    rate: 607.5,
  },
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: "₣",
    country: "French Polynesia",
    flag: "🇵🇫",
    timezone: "Pacific/Tahiti",
    locale: "fr-PF",
    rate: 109.5,
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    symbol: "﷼",
    country: "Yemen",
    flag: "🇾🇪",
    timezone: "Asia/Aden",
    locale: "ar-YE",
    rate: 250.0,
  },
  {
    code: "ZWL",
    name: "Zimbabwean Dollar",
    symbol: "Z$",
    country: "Zimbabwe",
    flag: "🇿🇼",
    timezone: "Africa/Harare",
    locale: "en-ZW",
    rate: 3619.0,
  },
  // Additional Asian currencies
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    country: "Kazakhstan",
    flag: "🇰🇿",
    timezone: "Asia/Almaty",
    locale: "kk-KZ",
    rate: 450.5,
  },
  {
    code: "KGS",
    name: "Kyrgyzstani Som",
    symbol: "с",
    country: "Kyrgyzstan",
    flag: "🇰🇬",
    timezone: "Asia/Bishkek",
    locale: "ky-KG",
    rate: 89.5,
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "SM",
    country: "Tajikistan",
    flag: "🇹🇯",
    timezone: "Asia/Dushanbe",
    locale: "tg-TJ",
    rate: 10.95,
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    symbol: "m",
    country: "Turkmenistan",
    flag: "🇹🇲",
    timezone: "Asia/Ashgabat",
    locale: "tk-TM",
    rate: 3.45,
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    country: "Afghanistan",
    flag: "🇦🇫",
    timezone: "Asia/Kabul",
    locale: "fa-AF",
    rate: 71.25,
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "֏",
    country: "Armenia",
    flag: "🇦🇲",
    timezone: "Asia/Yerevan",
    locale: "hy-AM",
    rate: 387.5,
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    country: "Azerbaijan",
    flag: "🇦🇿",
    timezone: "Asia/Baku",
    locale: "az-AZ",
    rate: 1.7,
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    country: "Georgia",
    flag: "🇬🇪",
    timezone: "Asia/Tbilisi",
    locale: "ka-GE",
    rate: 2.7,
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "ع.د",
    country: "Iraq",
    flag: "🇮🇶",
    timezone: "Asia/Baghdad",
    locale: "ar-IQ",
    rate: 1310.0,
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "JD",
    country: "Jordan",
    flag: "🇯🇴",
    timezone: "Asia/Amman",
    locale: "ar-JO",
    rate: 0.71,
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "KD",
    country: "Kuwait",
    flag: "🇰🇼",
    timezone: "Asia/Kuwait",
    locale: "ar-KW",
    rate: 0.31,
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "ل.ل",
    country: "Lebanon",
    flag: "🇱🇧",
    timezone: "Asia/Beirut",
    locale: "ar-LB",
    rate: 89500.0,
  },
  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "ر.ع.",
    country: "Oman",
    flag: "🇴🇲",
    timezone: "Asia/Muscat",
    locale: "ar-OM",
    rate: 0.39,
  },
  {
    code: "QAR",
    name: "Qatari Rial",
    symbol: "QR",
    country: "Qatar",
    flag: "🇶🇦",
    timezone: "Asia/Qatar",
    locale: "ar-QA",
    rate: 3.64,
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: "BD",
    country: "Bahrain",
    flag: "🇧🇭",
    timezone: "Asia/Bahrain",
    locale: "ar-BH",
    rate: 0.38,
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    symbol: "MOP$",
    country: "Macau",
    flag: "🇲🇴",
    timezone: "Asia/Macau",
    locale: "zh-MO",
    rate: 8.05,
  },
  {
    code: "MNT",
    name: "Mongolian Tögrög",
    symbol: "₮",
    country: "Mongolia",
    flag: "🇲🇳",
    timezone: "Asia/Ulaanbaatar",
    locale: "mn-MN",
    rate: 3385.0,
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "Rs",
    country: "Nepal",
    flag: "🇳🇵",
    timezone: "Asia/Kathmandu",
    locale: "ne-NP",
    rate: 132.85,
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    country: "Sri Lanka",
    flag: "🇱🇰",
    timezone: "Asia/Colombo",
    locale: "si-LK",
    rate: 298.5,
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    symbol: "Rf",
    country: "Maldives",
    flag: "🇲🇻",
    timezone: "Indian/Maldives",
    locale: "dv-MV",
    rate: 15.45,
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    country: "Bhutan",
    flag: "🇧🇹",
    timezone: "Asia/Thimphu",
    locale: "dz-BT",
    rate: 83.12,
  },
];

export const getCurrencyByCode = (code) => {
  return currencies.find((currency) => currency.code === code) || currencies[0];
};

export const formatCurrency = (amount, currency) => {
  const currencyData =
    typeof currency === "string" ? getCurrencyByCode(currency) : currency;
  return new Intl.NumberFormat(currencyData.locale, {
    style: "currency",
    currency: currencyData.code,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
};

export const convertCurrency = (amount, fromCurrency, toCurrency) => {
  const from =
    typeof fromCurrency === "string"
      ? getCurrencyByCode(fromCurrency)
      : fromCurrency;
  const to =
    typeof toCurrency === "string" ? getCurrencyByCode(toCurrency) : toCurrency;
  const usdAmount = amount / from.rate;
  return usdAmount * to.rate;
};
